---
- name: install Netbox
  hosts: prodNetbox
  gather_facts: true
  become: true  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    db_user: netbox
    db_name: netbox
    db_password: 'J5brHrAXFLQSif0K'
    #allow_world_readable_tmpfiles: true
    #ansible_sudo_pass: vagrant	
  roles:
   - role: deployNetbox