---
# tasks file for postgresql
# - name: update_system_and_install_packages_postgres
#   package:  
#     name: "{{ ubuntu_packages }}" 
#     update_cache: true 
#     state: latest
#   when: ansible_distribution == 'ubuntu'

- name: Ensure the PostgreSQL service is running
  service: 
    name: postgresql
    state: started
    enabled: yes
  become: true

- name: Check the version of installed postgres
  register: psqlVersion 
  command: "psql -V" 
- debug:
    var: psqlVersion.stdout

- name: Create the database
  become: true
  become_user: postgres
  postgresql_db: 
    name: "{{ db_name }}" 
    template: template0
    state: present

- name: Create postgres user for my app
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{db_user}}"
    password: "{{db_password}}"
    state: present

- name: GRANT ALL PRIVILEGES ON DATABASE netbox TO netbox
  become: true
  become_user: postgres
  postgresql_privs:
    db: "{{ db_name }}"
    type: database
    role: "{{ db_user }}"
    privs: ALL

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user: 
    db: "{{ db_name }}" 
    name: "{{ db_user }}"  
    password: "{{ db_password }}" 
    priv: ALL 
    state: present
